listener:
  protocol: HTTP
  host: localhost
  port: "8081"
  readTimeout: "30000"

ftp:
  workingDir: /
  host: test
  port: test
  username: test
  password: test

environment.id: local
domain: local
cloudhub.notifications.user: test
cloudhub.notifications.password: test
